'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
type C={id:number;catId:number;name:string;nameEn:string;vpn:boolean;iran:boolean;category:string;sources:{id:number|null}[]};
export default function Admin(){
 const[data,setData]=useState<C[]>([]),[q,setQ]=useState(''),[cat,setCat]=useState(''),[msg,setMsg]=useState('در حال دریافت کاتالوگ…'),[channelsFile,setChannelsFile]=useState<File|null>(null),[verifiedFile,setVerifiedFile]=useState<File|null>(null),[importing,setImporting]=useState(false);
 const load=()=>fetch('/api/catalog').then(r=>r.json()).then(j=>{setData(j.channels||[]);setMsg('Ready')}).catch(()=>setMsg('خطا در دریافت کاتالوگ'));
 useEffect(()=>{load()},[]);
 const cats=Array.from(new Map(data.map(c=>[c.catId,c.category])));
 const filtered=useMemo(()=>data.filter(c=>(!q||`${c.name} ${c.nameEn}`.toLowerCase().includes(q.toLowerCase()))&&(!cat||String(c.catId)===cat)),[data,q,cat]);
 const sources=data.reduce((n,c)=>n+c.sources.length,0);
 async function sync(){setMsg('در حال واکشی و sync کاتالوگ…');try{const r=await fetch('/api/admin/sync',{method:'POST',headers:{'x-admin-token':prompt('ADMIN_TOKEN')||''}});const j=await r.json();setMsg(j.message||j.error||'تمام شد');load()}catch{setMsg('خطای شبکه')}}
 async function syncEpg(){setMsg('در حال sync راهنمای برنامه‌ها…');try{const r=await fetch('/api/admin/epg',{method:'POST',headers:{'x-admin-token':prompt('ADMIN_TOKEN')||''}});const j=await r.json();setMsg(j.status==='unconfigured'?'EPG تنظیم نشده است':j.error||`EPG: ${j.programs||0} برنامه، ${j.matchedChannels||0} شبکه match شد`)}catch{setMsg('خطای شبکه در EPG')}}
 async function importCsv(){if(!channelsFile||!verifiedFile){setMsg('هر دو فایل CSV را انتخاب کنید');return}setImporting(true);setMsg('در حال import و deduplicate…');try{const form=new FormData();form.append('channels',channelsFile);form.append('verified',verifiedFile);const r=await fetch('/api/admin/catalog/import',{method:'POST',headers:{'x-admin-token':prompt('ADMIN_TOKEN')||''},body:form});const j=await r.json();setMsg(j.error||`Import: ${j.created||0} جدید، ${j.updated||0} بروزرسانی، ${j.sourcesCreated||0} source جدید، ${j.sourcesSkipped||0} تکراری`);if(r.ok||r.status===207)load()}catch{setMsg('خطا در import CSV')}finally{setImporting(false)}}
 return <main><header className="top"><div><div className="brand">MOM<span>SAT</span></div><div className="muted">Control Center</div></div><nav><Link href="/">نمایش</Link><Link href="/browse">کاتالوگ</Link><Link href="/guide">EPG / راهنما</Link></nav></header><div className="eyebrow">ADMIN / INGESTION / DATABASE</div><h1>مدیریت کاتالوگ</h1><div className="notice">منابع کاتالوگ مستقل هستند. mytvsat اختیاری است و بدون AES credentials کل سیستم را متوقف نمی‌کند. EPG از XMLTV جداگانه sync می‌شود.</div><div className="admin-kpis"><div className="kpi"><span className="muted">Channels</span><strong>{data.length}</strong></div><div className="kpi"><span className="muted">Sources</span><strong>{sources}</strong></div><div className="kpi"><span className="muted">Categories</span><strong>{cats.length}</strong></div><div className="kpi"><span className="muted">VPN</span><strong>{data.filter(c=>c.vpn).length}</strong></div></div><div className="admin-tools"><input className="status" style={{minWidth:250}} value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو…"/><select className="status" value={cat} onChange={e=>setCat(e.target.value)}><option value="">همه دسته‌ها</option>{cats.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select><button className="btn primary" onClick={sync}>Fetch + Sync</button><button className="btn" onClick={syncEpg}>Sync EPG</button><span className="status">{msg}</span></div><section className="notice" style={{marginTop:16}}><strong>CSV Catalog Import</strong><div className="muted" style={{margin:'6px 0 12px'}}>دو فایل v2_posts_channels.csv و v2_posts_verified.csv را انتخاب کنید. import دوباره idempotent است و کانال/source تکراری ایجاد نمی‌کند.</div><div style={{display:'flex',gap:10,flexWrap:'wrap',alignItems:'center'}}><label className="btn">Channels CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>setChannelsFile(e.target.files?.[0]||null)}/></label><span className="status">{channelsFile?.name||'انتخاب نشده'}</span><label className="btn">Verified CSV<input hidden type="file" accept=".csv,text/csv" onChange={e=>setVerifiedFile(e.target.files?.[0]||null)}/></label><span className="status">{verifiedFile?.name||'انتخاب نشده'}</span><button className="btn primary" disabled={importing} onClick={importCsv}>{importing?'Importing…':'Import CSV + Deduplicate'}</button></div></section><div style={{overflowX:'auto',marginTop:16}}><table className="admin-table"><thead><tr><th>ID</th><th>نام</th><th>دسته</th><th>VPN</th><th>Iran</th><th>Sources</th><th></th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td>{c.id}</td><td>{c.name}<div className="muted">{c.nameEn}</div></td><td>{c.category}</td><td>{c.vpn?'YES':'NO'}</td><td>{c.iran?'YES':'NO'}</td><td>{c.sources.length}</td><td><Link href={`/channel/${c.id}`} className="more">View</Link></td></tr>)}</tbody></table></div></main>
}