'use client';

import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';

type CatalogChannel = { id: number; catId: number; name: string; nameEn: string; vpn: boolean; iran: boolean; category: string; platform?: string | null; satellite?: string | null; frequency?: string | null; sources: { id: number | null }[] };
type PreviewRow = { row: number; type: string; name?: string; nameEn?: string; url?: string; group?: string; category?: string; country?: string; satellite?: string; frequency?: string; extra?: string };
type ImportPhase = 'reading' | 'analyzing' | 'uploading' | 'processing' | 'done' | 'error';
type ServerTiming = Record<string, number>;
type ImportResult = { ok?: boolean; detectedTable?: string; confidence?: number; reason?: string; format?: string; rows: number; created: number; updated: number; skipped: number; errors: string[]; ingestion?: { channelsCreated?: number; channelsMatched?: number; sourcesCreated?: number; sourcesSkipped?: number }; database?: { categories?: number; channels?: number; sources?: number; programs?: number }; timing?: ServerTiming; error?: string };
type UploadState = { id: string; file: File; phase: ImportPhase; status: 'sending' | 'done' | 'error'; readProgress: number; analysisProgress: number; uploadProgress: number; serverElapsedMs: number; startedAt: number; preview: PreviewRow[]; totalRows: number; detectedFormat: string; currentStep: string; result?: ImportResult; error?: string };

const PREVIEW_LIMIT = 200;
const MAX_UPLOAD_BYTES = 10 * 1024 * 1024;
const formats = '.csv,.json,.m3u,.m3u8';

function sleep(ms: number) { return new Promise<void>((resolve) => setTimeout(resolve, ms)); }
function csvPreview(text: string): Array<Record<string, string>> { const input = text.replace(/^\uFEFF/, ''); const rows: string[][] = []; let row: string[] = []; let cell = ''; let quoted = false; for (let i = 0; i < input.length; i += 1) { const ch = input[i]; if (ch === '"') { if (quoted && input[i + 1] === '"') { cell += '"'; i += 1; } else quoted = !quoted; } else if (ch === ',' && !quoted) { row.push(cell); cell = ''; } else if ((ch === '\n' || ch === '\r') && !quoted) { if (ch === '\r' && input[i + 1] === '\n') i += 1; row.push(cell); cell = ''; if (row.some((value) => value.trim() !== '')) rows.push(row); row = []; } else cell += ch; } if (cell || row.length) { row.push(cell); if (row.some((value) => value.trim() !== '')) rows.push(row); } if (!rows.length) return []; const headers = rows.shift()!.map((header, index) => header.trim() || `column_${index + 1}`); return rows.map((values) => Object.fromEntries(headers.map((header, index) => [header, (values[index] ?? '').trim()]))); }
function attrValue(header: string, key: string) { return header.match(new RegExp(`${key}="([^"]*)"`, 'i'))?.[1]?.trim() || ''; }
function m3uPreview(text: string): Array<Record<string, string>> { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/); const entries: Array<Record<string, string>> = []; let pending: Record<string, string> | null = null; let pendingRef = ''; let pendingOrigin = ''; for (const raw of lines) { const line = raw.trim(); if (!line || line === '#EXTM3U') continue; if (line.startsWith('#EXTINF:')) { const comma = line.indexOf(','); const header = comma >= 0 ? line.slice(0, comma) : line; const displayName = comma >= 0 ? line.slice(comma + 1).trim() : ''; pending = { name: attrValue(header, 'tvg-name') || displayName || attrValue(header, 'tvg-id') || 'Unnamed channel', nameEn: attrValue(header, 'tvg-name') || attrValue(header, 'tvg-id') || displayName, group: attrValue(header, 'group-title'), country: attrValue(header, 'tvg-country') || attrValue(header, 'country'), satellite: attrValue(header, 'satellite') || attrValue(header, 'sat'), frequency: attrValue(header, 'frequency') || attrValue(header, 'freq') }; pendingRef = ''; pendingOrigin = ''; continue; } if (line.startsWith('#EXTVLCOPT:') && pending) { const directive = line.slice('#EXTVLCOPT:'.length); const separator = directive.indexOf('='); const key = (separator >= 0 ? directive.slice(0, separator) : directive).trim().toLowerCase(); const value = separator >= 0 ? directive.slice(separator + 1).trim() : ''; if (key.includes('referer')) pendingRef = value; if (key === 'http-origin') pendingOrigin = value; continue; } if (line.startsWith('#EXTHTTP:') && pending) { try { const payload = JSON.parse(line.slice('#EXTHTTP:'.length).trim()) as Record<string, unknown>; pendingRef = String(payload.Referer ?? payload.referer ?? payload['http-referrer'] ?? pendingRef).trim(); pendingOrigin = String(payload.Origin ?? payload.origin ?? pendingOrigin).trim(); } catch {} continue; } if (line.startsWith('#') || !pending || !/^https?:\/\//i.test(line)) continue; entries.push({ ...pending, url: line, referer: pendingRef, origin: pendingOrigin }); pending = null; } return entries; }
function jsonPreview(text: string): Array<Record<string, unknown>> { const payload = JSON.parse(text.replace(/^\uFEFF/, '')) as unknown; if (Array.isArray(payload)) return payload.filter((value) => Boolean(value && typeof value === 'object')) as Array<Record<string, unknown>>; if (payload && typeof payload === 'object') { const object = payload as Record<string, unknown>; for (const key of ['rows', 'data', 'channels', 'sources', 'programs', 'categories', 'posts']) if (Array.isArray(object[key])) return object[key].filter((value) => Boolean(value && typeof value === 'object')) as Array<Record<string, unknown>>; } return []; }
function detectFormat(fileName: string, text: string) { const lower = fileName.toLowerCase(); const trimmed = text.trimStart(); if (lower.endsWith('.m3u') || lower.endsWith('.m3u8') || trimmed.startsWith('#EXTM3U')) return 'm3u'; if (lower.endsWith('.json') || trimmed.startsWith('{') || trimmed.startsWith('[')) return 'json'; return 'csv'; }
function buildPreview(fileName: string, text: string) { const format = detectFormat(fileName, text); if (format === 'm3u') return m3uPreview(text); if (format === 'json') return jsonPreview(text); return csvPreview(text); }
function rowToPreview(row: Record<string, unknown>, index: number, format: string): PreviewRow { const pick = (...keys: string[]) => { for (const key of keys) { const normalized = key.trim().toLowerCase().replace(/[\s-]+/g, '_'); const hit = Object.keys(row).find((candidate) => candidate.trim().toLowerCase().replace(/[\s-]+/g, '_') === normalized); if (hit) return String(row[hit] ?? ''); } return ''; }; return { row: index + 1, type: format === 'm3u' ? 'Channel + Source' : 'Detected row', name: pick('name', 'channel_name', 'channelname', 'title', 'program_title'), nameEn: pick('name_en', 'channel_name_en', 'nameen'), url: pick('url', 'channel_url', 'source_url', 'stream_url'), group: pick('group-title', 'group_title', 'category', 'category_name'), category: pick('category', 'category_name'), country: pick('country', 'tvg-country'), satellite: pick('satellite', 'sat'), frequency: pick('frequency', 'freq'), extra: format === 'json' ? JSON.stringify(row).slice(0, 240) : '' }; }
function xhrUpload(url: string, form: FormData, token: string, onProgress: (value: number) => void) { return new Promise<{ status: number; body: ImportResult }>((resolve, reject) => { const xhr = new XMLHttpRequest(); xhr.open('POST', url); if (token) xhr.setRequestHeader('x-admin-token', token); xhr.upload.onprogress = (event) => { if (event.lengthComputable) onProgress(Math.round((event.loaded / event.total) * 100)); }; xhr.onload = () => { try { resolve({ status: xhr.status, body: JSON.parse(xhr.responseText || '{}') }); } catch { reject(new Error('Invalid server response')); } }; xhr.onerror = () => reject(new Error('Network error')); xhr.onabort = () => reject(new Error('Upload aborted')); xhr.send(form); }); }
function formatDuration(ms: number) { if (!Number.isFinite(ms)) return '—'; if (ms < 1000) return `${Math.max(1, Math.round(ms))} ms`; const seconds = Math.floor(ms / 1000); return seconds < 60 ? `${seconds}s` : `${Math.floor(seconds / 60)}m ${seconds % 60}s`; }
function statusLabel(phase: ImportPhase) { return ({ reading: 'خواندن فایل', analyzing: 'تحلیل ساختار', uploading: 'آپلود', processing: 'پردازش سرور', done: 'تکمیل', error: 'خطا' })[phase]; }
function overallProgress(upload: UploadState) { if (upload.phase === 'reading') return Math.round(upload.readProgress * 0.1); if (upload.phase === 'analyzing') return 10 + Math.round(upload.analysisProgress * 0.2); if (upload.phase === 'uploading') return 30 + Math.round(upload.uploadProgress * 0.15); if (upload.phase === 'processing') return 45; if (upload.phase === 'done') return 100; return 0; }
function prettyTimingKey(key: string) { return ({ request: 'کل درخواست HTTP', formData: 'خواندن FormData', readFile: 'خواندن فایل روی سرور', parse: 'Parse رکوردها', detect: 'تشخیص نوع جدول', serialize: 'تبدیل JSON به CSV', import: 'پردازش و ثبت اصلی', databaseCounts: 'شمارش رکوردهای دیتابیس', total: 'کل import داخلی' } as Record<string, string>)[key] || key; }

export default function Admin() {
  const [data, setData] = useState<CatalogChannel[]>([]);
  const [q, setQ] = useState('');
  const [cat, setCat] = useState('');
  const [msg, setMsg] = useState('آماده');
  const [uploads, setUploads] = useState<UploadState[]>([]);
  const [token, setToken] = useState('');
  const [now, setNow] = useState(Date.now());

  const loadCatalog = () => fetch('/api/catalog').then((response) => response.json()).then((json) => { setData(json.channels || []); setMsg('آماده'); }).catch(() => setMsg('خطا در دریافت کاتالوگ'));
  useEffect(() => { setToken(window.localStorage.getItem('momsat-admin-token') || ''); loadCatalog(); }, []);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 250); return () => window.clearInterval(timer); }, []);
  const patchUpload = (id: string, patch: Partial<UploadState>) => setUploads((items) => items.map((item) => item.id === id ? { ...item, ...patch } : item));
  const cats = Array.from(new Map(data.map((channel) => [channel.catId, channel.category])));
  const filtered = useMemo(() => data.filter((channel) => (!q || `${channel.name} ${channel.nameEn}`.toLowerCase().includes(q.toLowerCase())) && (!cat || String(channel.catId) === cat)), [data, q, cat]);
  const sourceCount = data.reduce((sum, channel) => sum + channel.sources.length, 0);

  async function prepareFile(file: File) {
    const id = `${Date.now()}-${Math.random().toString(36).slice(2)}`;
    const startedAt = Date.now();
    const initial: UploadState = { id, file, phase: 'reading', status: 'sending', readProgress: 0, analysisProgress: 0, uploadProgress: 0, serverElapsedMs: 0, startedAt, preview: [], totalRows: 0, detectedFormat: '', detectedTable: 'در حال تشخیص…', currentStep: 'خواندن فایل در مرورگر' } as UploadState;
    setUploads((items) => [initial, ...items]);
    if (file.size > MAX_UPLOAD_BYTES) { patchUpload(id, { phase: 'error', status: 'error', currentStep: 'فایل بزرگ‌تر از سقف 10MB است', error: 'Maximum file size is 10 MB.' }); return; }
    try {
      const text = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onprogress = (event) => { const progress = event.lengthComputable ? Math.round((event.loaded / event.total) * 100) : 0; patchUpload(id, { readProgress: progress, currentStep: `خواندن فایل در مرورگر: ${progress}%` }); }; reader.onload = () => { patchUpload(id, { readProgress: 100 }); resolve(String(reader.result || '')); }; reader.onerror = () => reject(new Error('خواندن فایل ناموفق بود')); reader.readAsText(file); });
      const format = detectFormat(file.name, text);
      patchUpload(id, { phase: 'analyzing', detectedFormat: format, currentStep: 'ساخت preview و شمارش واقعی رکوردها' });
      await sleep(0);
      const rawRows = buildPreview(file.name, text);
      const preview = rawRows.slice(0, PREVIEW_LIMIT).map((row, index) => rowToPreview(row, index, format));
      patchUpload(id, { analysisProgress: 100, totalRows: rawRows.length, preview, detectedFormat: format, currentStep: `تحلیل تمام شد؛ ${rawRows.length.toLocaleString()} رکورد شناسایی شد` });

      const form = new FormData();
      form.append('file', file);
      patchUpload(id, { phase: 'uploading', uploadProgress: 0, currentStep: 'ارسال فایل به سرور' });
      const responseStart = Date.now();
      const requestPromise = xhrUpload('/api/admin/table-import', form, token, (progress) => patchUpload(id, { uploadProgress: progress, currentStep: progress < 100 ? `آپلود واقعی فایل: ${progress}%` : 'آپلود کامل شد؛ پاسخ backend در حال پردازش است…' }));
      patchUpload(id, { phase: 'processing', currentStep: 'سرور در حال تشخیص schema، تطبیق کانال‌ها و ثبت رکوردهاست' });
      const response = await requestPromise;
      patchUpload(id, { serverElapsedMs: Date.now() - responseStart });
      if (response.status >= 400 || response.body.ok === false) throw new Error(response.body.error || `Import failed with HTTP ${response.status}`);
      patchUpload(id, { phase: 'done', status: 'done', currentStep: 'Import کامل شد', result: response.body });
      setMsg(`Import موفق: ${Number(response.body.rows || rawRows.length).toLocaleString()} رکورد`);
      await loadCatalog();
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Import failed';
      patchUpload(id, { phase: 'error', status: 'error', serverElapsedMs: Date.now() - startedAt, currentStep: message, error: message });
      setMsg(message);
    }
  }

  function onFileChange(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ''; if (file) void prepareFile(file); }

  return <main style={{ minHeight: '100vh', padding: 24, background: '#0b1020', color: '#eef2ff', fontFamily: 'system-ui, sans-serif' }}><div style={{ maxWidth: 1500, margin: '0 auto' }}>
    <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16, marginBottom: 24 }}><div><div style={{ fontSize: 12, opacity: .6, letterSpacing: 1 }}>MOMSAT ADMIN</div><h1 style={{ margin: '6px 0 0', fontSize: 30 }}>Import و مدیریت کاتالوگ</h1></div><Link href="/browse" style={{ color: '#7dd3fc', textDecoration: 'none' }}>بازگشت به Browse</Link></header>
    <section style={{ display: 'grid', gridTemplateColumns: 'minmax(0,1.4fr) minmax(320px,.6fr)', gap: 18 }}>
      <div style={{ background: '#11182b', border: '1px solid #22304e', borderRadius: 16, padding: 20 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 16 }}><div><h2 style={{ margin: 0, fontSize: 20 }}>پردازش زنده فایل</h2><p style={{ margin: '6px 0 0', opacity: .7 }}>در فایل‌های کوچک، کل CSV یک‌بار ارسال می‌شود؛ chunkهای 50تایی تکراری حذف شده‌اند.</p></div><label style={{ border: '1px solid #33466e', borderRadius: 10, padding: '10px 14px', cursor: 'pointer', background: '#17233c' }}>انتخاب فایل<input type="file" accept={formats} onChange={onFileChange} style={{ display: 'none' }} /></label></div>
        {uploads.map((upload) => { const progress = overallProgress(upload); const timing = upload.result?.timing; const sortedTimings = timing ? Object.entries(timing).sort((a, b) => b[1] - a[1]) : []; const liveElapsed = upload.phase === 'processing' ? now - upload.startedAt : upload.serverElapsedMs || now - upload.startedAt; return <article key={upload.id} style={{ marginTop: 18, background: '#0c1425', border: '1px solid #22304e', borderRadius: 14, padding: 16 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', gap: 16 }}><div><strong>{upload.file.name}</strong><div style={{ marginTop: 5, fontSize: 12, opacity: .6 }}>{(upload.file.size / 1024).toFixed(1)} KB · {upload.detectedFormat || 'format در حال تشخیص'} · {upload.totalRows ? `${upload.totalRows.toLocaleString()} رکورد` : 'تعداد در حال محاسبه'}</div></div><span style={{ fontSize: 13, opacity: .8 }}>{statusLabel(upload.phase)}</span></div>
          <div style={{ marginTop: 14, height: 10, background: '#1b2740', borderRadius: 999, overflow: 'hidden' }}><div style={{ width: `${progress}%`, height: '100%', background: '#38bdf8', transition: 'width .15s linear' }} /></div>
          <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8, fontSize: 12 }}><span>پیشرفت مرحله‌ای: {progress}%{upload.phase === 'processing' ? ' · درصد backend عمداً ساختگی نیست' : ''}</span><span>زمان سپری‌شده: {formatDuration(now - upload.startedAt)}</span></div>
          <div style={{ marginTop: 12, display: 'grid', gridTemplateColumns: 'repeat(5,minmax(0,1fr))', gap: 7 }}>{(['reading','analyzing','uploading','processing','done'] as ImportPhase[]).map((phase) => { const order = ['reading','analyzing','uploading','processing','done']; const current = order.indexOf(upload.phase); const thisIndex = order.indexOf(phase); const complete = upload.phase !== 'error' && thisIndex <= current; return <div key={phase} style={{ padding: 8, borderRadius: 8, border: `1px solid ${complete ? '#2f6f9f' : '#273450'}`, background: complete ? '#10253b' : '#10192c', textAlign: 'center', fontSize: 11 }}>{statusLabel(phase)}</div>; })}</div>
          <div style={{ marginTop: 12, padding: 12, borderRadius: 10, background: '#101a30' }}><strong>{upload.currentStep}</strong>{upload.phase === 'processing' && <div style={{ marginTop: 7, fontSize: 12, opacity: .72 }}>مرورگر در این مرحله منتظر پاسخ سرور است. تایمر بالا واقعی است و نشان می‌دهد backend چند ثانیه بدون گزارش درصد داخلی کار کرده است.</div>}{upload.phase === 'processing' && <div style={{ marginTop: 7, fontSize: 13 }}>زمان انتظار backend: <strong>{formatDuration(liveElapsed)}</strong></div>}</div>
          {upload.result && <div style={{ marginTop: 14 }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4,minmax(0,1fr))', gap: 8 }}>{[['Table', upload.result.detectedTable || '—'],['Rows', Number(upload.result.rows || 0).toLocaleString()],['Created', Number(upload.result.created || 0).toLocaleString()],['Skipped', Number(upload.result.skipped || 0).toLocaleString()]].map(([label, value]) => <div key={label} style={{ background: '#101a30', borderRadius: 10, padding: 10 }}><div style={{ fontSize: 11, opacity: .6 }}>{label}</div><strong>{value}</strong></div>)}</div>
            {upload.result.ingestion && <div style={{ marginTop: 10, fontSize: 12, opacity: .8 }}>Matched channels: {Number(upload.result.ingestion.channelsMatched || 0).toLocaleString()} · New channels: {Number(upload.result.ingestion.channelsCreated || 0).toLocaleString()} · New sources: {Number(upload.result.ingestion.sourcesCreated || 0).toLocaleString()} · Skipped sources: {Number(upload.result.ingestion.sourcesSkipped || 0).toLocaleString()}</div>}
            {sortedTimings.length > 0 && <div style={{ marginTop: 14, borderTop: '1px solid #22304e', paddingTop: 13 }}><div style={{ fontWeight: 700, marginBottom: 7 }}>دقیقاً چه کاری طول کشید؟</div>{sortedTimings.map(([key, value]) => <div key={key} style={{ display: 'flex', justifyContent: 'space-between', gap: 14, padding: '5px 0', fontSize: 12 }}><span>{prettyTimingKey(key)}</span><strong>{formatDuration(value)}</strong></div>)}</div>}</div>}
          {upload.error && <div style={{ marginTop: 12, color: '#fda4af', fontSize: 13 }}>خطا: {upload.error}</div>}
          {upload.preview.length > 0 && <div style={{ marginTop: 14 }}><div style={{ fontSize: 11, opacity: .55, letterSpacing: 1 }}>RECORD PREVIEW / FIRST {upload.preview.length}</div><div style={{ overflow: 'auto', marginTop: 8, maxHeight: 380, border: '1px solid #22304e', borderRadius: 10 }}><table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}><thead><tr style={{ background: '#111d34', position: 'sticky', top: 0 }}><th style={{ padding: 8, textAlign: 'left' }}>#</th><th style={{ padding: 8, textAlign: 'left' }}>Type</th><th style={{ padding: 8, textAlign: 'left' }}>Name</th><th style={{ padding: 8, textAlign: 'left' }}>URL</th><th style={{ padding: 8, textAlign: 'left' }}>Category</th><th style={{ padding: 8, textAlign: 'left' }}>Country</th><th style={{ padding: 8, textAlign: 'left' }}>Satellite</th><th style={{ padding: 8, textAlign: 'left' }}>Frequency</th></tr></thead><tbody>{upload.preview.map((row) => <tr key={`${upload.id}-${row.row}`} style={{ borderTop: '1px solid #1d2941' }}><td style={{ padding: 8 }}>{row.row}</td><td style={{ padding: 8 }}>{row.type}</td><td style={{ padding: 8, minWidth: 160 }}>{row.name || row.nameEn || '—'}</td><td style={{ padding: 8, minWidth: 280, maxWidth: 420, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{row.url || '—'}</td><td style={{ padding: 8 }}>{row.category || row.group || '—'}</td><td style={{ padding: 8 }}>{row.country || '—'}</td><td style={{ padding: 8 }}>{row.satellite || '—'}</td><td style={{ padding: 8 }}>{row.frequency || '—'}</td></tr>)}</tbody></table></div></div>}
        </article>; })}
      </div>
      <aside style={{ display: 'grid', gap: 18, alignContent: 'start' }}>
        <div style={{ background: '#11182b', border: '1px solid #22304e', borderRadius: 16, padding: 18 }}><div style={{ fontSize: 12, opacity: .6 }}>CATALOG STATUS</div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10, marginTop: 12 }}><div style={{ padding: 12, background: '#0c1425', borderRadius: 10 }}><div style={{ opacity: .6, fontSize: 11 }}>Channels</div><strong style={{ fontSize: 22 }}>{data.length}</strong></div><div style={{ padding: 12, background: '#0c1425', borderRadius: 10 }}><div style={{ opacity: .6, fontSize: 11 }}>Sources</div><strong style={{ fontSize: 22 }}>{sourceCount}</strong></div></div><div style={{ marginTop: 12, fontSize: 12, opacity: .7 }}>{msg}</div></div>
        <div style={{ background: '#11182b', border: '1px solid #22304e', borderRadius: 16, padding: 18 }}><div style={{ fontWeight: 700 }}>Catalog Filter</div><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="جستجوی شبکه…" style={{ width: '100%', marginTop: 10, boxSizing: 'border-box', background: '#0c1425', color: '#fff', border: '1px solid #273654', borderRadius: 9, padding: 10 }} /><select value={cat} onChange={(event) => setCat(event.target.value)} style={{ width: '100%', marginTop: 8, boxSizing: 'border-box', background: '#0c1425', color: '#fff', border: '1px solid #273654', borderRadius: 9, padding: 10 }}><option value="">همه دسته‌ها</option>{cats.map(([id, name]) => <option key={String(id)} value={String(id)}>{String(name)}</option>)}</select><div style={{ marginTop: 10, fontSize: 12, opacity: .65 }}>نمایش {filtered.length.toLocaleString()} شبکه</div></div>
        <div style={{ background: '#11182b', border: '1px solid #22304e', borderRadius: 16, padding: 18 }}><div style={{ fontWeight: 700 }}>منطق زمان‌سنجی جدید</div><div style={{ marginTop: 10, fontSize: 12, lineHeight: 1.9, opacity: .76 }}>خواندن فایل و preview داخل مرورگر زمان‌سنجی می‌شوند.<br />درخواست HTTP درصد واقعی آپلود را گزارش می‌کند.<br />بعد از 100٪ آپلود، backend بدون درصد جعلی به‌عنوان «در انتظار پاسخ» نمایش داده می‌شود.<br />پس از پاسخ، زمان parse / detect / import / database count جداگانه نمایش داده می‌شود.</div></div>
      </aside>
    </section>
  </div></main>;
}
