'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import ControlCenterNav from '../ControlCenterNav';
import styles from './database-manager.module.css';

type Source={id:number|null;title:string|null;url:string;referer:string|null;origin:string|null;country:string|null;vip:boolean};
type Channel={id:number;catId:number;name:string;nameEn:string;image:string|null;url:string;referer:string|null;origin:string|null;vpn:boolean;iran:boolean;popular:number|string;vip:boolean;language:string|null;country:string|null;platform:string|null;satellite:string|null;frequency:string|null;polarization:string|null;symbolRate:string|null;serviceId:string|null;category:string;categoryEn:string;sources:Source[]};
type Data={database:{channels:Channel[];categories:{id:number;name:string;nameEn:string}[]};csv:{channels:Channel[]};counts:Record<string,number>};
type Form=Channel;
const blank:Form={id:0,catId:0,name:'',nameEn:'',image:'',url:'',referer:'',origin:'',vpn:false,iran:false,popular:0,vip:false,language:'',country:'',platform:'',satellite:'',frequency:'',polarization:'',symbolRate:'',serviceId:'',category:'',categoryEn:'',sources:[]};
const headers=(token:string)=>({'content-type':'application/json','x-admin-token':token});
const norm=(c:Channel)=>({...c,popular:Number(c.popular||0),sources:(c.sources||[]).map(s=>({...s}))});
function esc(v:unknown){const s=String(v??'');return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function downloadCsv(rows:Channel[]){const h=['channel_id','category_id','channel_name','channel_name_en','channel_image','channel_url','channel_referer','channel_agent','channel_origin','need_vpn','for_iran','popular','isvip','category_name','category_name_en','channel_headers','sourses'];const b=rows.map(c=>[c.id,c.catId,c.name,c.nameEn,c.image,c.url,c.referer,'',c.origin,c.vpn?1:0,c.iran?1:0,c.popular,c.vip?1:0,c.category,c.categoryEn,'',JSON.stringify(c.sources.map(s=>({ID:s.id,title:s.title,channel_url:s.url,channel_referer:s.referer,channel_origin:s.origin,country:s.country,isvip:s.vip?1:0,channel_headers:null})))].map(esc).join(',')).join('\n');const blob=new Blob([h.join(',')+'\n'+b+'\n'],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='momsat-seed-data-edited.csv';a.click();}

export default function DatabaseManagerPage(){
 const[token,setToken]=useState(''),[data,setData]=useState<Data|null>(null),[tab,setTab]=useState<'db'|'csv'|'diff'>('diff'),[query,setQuery]=useState(''),[selected,setSelected]=useState<number|null>(null),[form,setForm]=useState<Form>(blank),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{try{const r=await fetch('/api/admin/table-manager',{headers:{'x-admin-token':token},cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'خطا در دریافت اطلاعات');setData(j);setMessage('اطلاعات به‌روز شد')}catch(e){setMessage(e instanceof Error?e.message:'خطا')}};
 useEffect(()=>setToken(localStorage.getItem('momsat-admin-token')||''),[]);useEffect(()=>{if(token)void load()},[token]);
 const db=data?.database.channels||[],csv=data?.csv.channels||[],dbMap=useMemo(()=>new Map(db.map(c=>[c.id,c])),[db]);
 const diffs=useMemo(()=>csv.filter(c=>{const d=dbMap.get(c.id);return !d||JSON.stringify(norm(d))!==JSON.stringify(norm(c))}),[csv,dbMap]);
 const visible=useMemo(()=>{const src=tab==='db'?db:tab==='csv'?csv:diffs;const q=query.trim().toLowerCase();return q?src.filter(c=>`${c.id} ${c.name} ${c.nameEn} ${c.category} ${c.url}`.toLowerCase().includes(q)):src},[tab,db,csv,diffs,query]);
 const pick=(c:Channel)=>{setSelected(c.id);setForm(norm(c))};
 const newRow=()=>{setSelected(null);setForm({...blank,id:Math.max(0,...csv.map(c=>c.id),...db.map(c=>c.id))+1})};
 const patch=(k:keyof Form,v:unknown)=>setForm(f=>({...f,[k]:v}));
 const save=async()=>{const c=norm(form);if(!c.name||!c.nameEn||!c.url)return setMessage('نام فارسی، نام انگلیسی و URL الزامی است.');if(tab==='csv'){setData(d=>d?{...d,csv:{channels:d.csv.channels.some(x=>x.id===c.id)?d.csv.channels.map(x=>x.id===c.id?c:x):[...d.csv.channels,c]}}:d);setMessage('تغییر CSV محلی شد؛ برای اعمال روی DB از Sync استفاده کن.');setSelected(c.id);return}setBusy(true);try{const r=await fetch('/api/admin/table-manager/sync-edited',{method:'POST',headers:headers(token),body:JSON.stringify({channels:[c],fullSync:false})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'ذخیره ناموفق');setMessage('در DB ذخیره شد');await load()}catch(e){setMessage(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}};
 const remove=async()=>{if(!selected||!confirm(tab==='csv'?'رکورد CSV حذف شود؟':'شبکه از DB حذف شود؟'))return;if(tab==='csv'){setData(d=>d?{...d,csv:{channels:d.csv.channels.filter(c=>c.id!==selected)}}:d);setSelected(null);setForm(blank);return}setBusy(true);try{const r=await fetch('/api/admin/table-manager',{method:'POST',headers:headers(token),body:JSON.stringify({action:'delete-channel',channel:{id:selected}})});const j=await r.json();if(!r.ok)throw Error(j.error||'حذف ناموفق');await load();setSelected(null);setForm(blank);setMessage('شبکه حذف شد')}catch(e){setMessage(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}};
 const sync=async()=>{if(!confirm(`تمام ${csv.length} رکورد CSV روی DB اعمال می‌شود و موارد خارج از CSV حذف می‌شوند. ادامه؟`))return;setBusy(true);try{const r=await fetch('/api/admin/table-manager/sync-edited',{method:'POST',headers:headers(token),body:JSON.stringify({channels:csv,fullSync:true})});const j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Sync ناموفق');setMessage(`Sync کامل شد: ${j.created||0} ایجاد، ${j.updated||0} بروزرسانی، ${j.channelsDeleted||0} حذف`);await load()}catch(e){setMessage(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}};
 const sourcePatch=(i:number,p:Partial<Source>)=>setForm(f=>({...f,sources:f.sources.map((s,n)=>n===i?{...s,...p}:s)}));
 const addSource=()=>setForm(f=>({...f,sources:[...f.sources,{id:null,title:'',url:'',referer:'',origin:'',country:'',vip:false}]}));
 const delSource=(i:number)=>setForm(f=>({...f,sources:f.sources.filter((_,n)=>n!==i)}));
 const field=(k:keyof Form,label:string,wide=false)=><label className={styles.field} style={wide?{gridColumn:'1/-1'}:undefined}><span className={styles.label}>{label}</span><input value={String(form[k]??'')} onChange={e=>patch(k,e.target.value)}/></label>;
 return <main className={styles.page} dir="rtl"><div className={styles.shell}><ControlCenterNav/><header className={styles.hero}><div><span className={styles.eyebrow}>DATA CONTROL CENTER</span><h1 className={styles.title}>مدیریت کاتالوگ و Seed Data</h1><p className={styles.sub}>DB و فایل seed-data را در یک محیط مدیریتی مقایسه، ویرایش و همگام کن. هر تغییر قبل از Sync قابل بررسی است.</p></div><div className={styles.heroActions}><Link href="/admin">بازگشت</Link><button onClick={()=>void load()}>↻ بروزرسانی</button></div></header>
 <section className={styles.stats}><div className={styles.stat}><span className={styles.statLabel}>رکوردهای DB</span><strong className={styles.statValue}>{db.length.toLocaleString()}</strong></div><div className={styles.stat}><span className={styles.statLabel}>رکوردهای CSV</span><strong className={styles.statValue}>{csv.length.toLocaleString()}</strong></div><div className={styles.stat}><span className={styles.statLabel}>اختلاف‌ها</span><strong className={styles.statValue}>{diffs.length.toLocaleString()}</strong></div><div className={styles.stat}><span className={styles.statLabel}>دسته‌ها</span><strong className={styles.statValue}>{data?.database.categories.length||0}</strong></div></section>
 <div className={styles.layout}><section className={styles.main}><div className={styles.toolbar}><div className={styles.tabs}><button className={`${styles.tab} ${tab==='diff'?styles.tabActive:''}`} onClick={()=>setTab('diff')}>اختلاف‌ها <b>{diffs.length}</b></button><button className={`${styles.tab} ${tab==='db'?styles.tabActive:''}`} onClick={()=>setTab('db')}>DB <b>{db.length}</b></button><button className={`${styles.tab} ${tab==='csv'?styles.tabActive:''}`} onClick={()=>setTab('csv')}>CSV <b>{csv.length}</b></button></div><input className={styles.search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="جستجوی نام، ID، URL یا دسته…"/></div>
 <div className={styles.toolbar}><button className={styles.sync} disabled={busy||!csv.length} onClick={()=>void sync()}>⟳ Sync کامل CSV → DB</button><button onClick={newRow}>＋ شبکه جدید</button><button onClick={()=>downloadCsv(csv)}>↓ خروجی CSV</button><span className={styles.note}>{message}</span></div>
 <span className={styles.mobileHint}>برای ویرایش یک ردیف را انتخاب کن.</span><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>ID</th><th>شبکه</th><th>English</th><th>دسته</th><th>Stream</th><th>Sources</th><th>وضعیت</th></tr></thead><tbody>{visible.map(c=>{const d=dbMap.get(c.id);const mismatch=!d||JSON.stringify(norm(d))!==JSON.stringify(norm(c));return <tr key={c.id} className={`${styles.row} ${selected===c.id?styles.selected:''}`} onClick={()=>pick(c)}><td>{c.id}</td><td className={styles.name}>{c.name}</td><td className={styles.en}>{c.nameEn}</td><td>{c.category||'—'}</td><td className={styles.url} dir="ltr">{c.url}</td><td>{c.sources.length}</td><td><span className={`${styles.badge} ${tab==='diff'?(mismatch?styles.warn:styles.ok):styles.ok}`}>{tab==='diff'?(mismatch?'تغییر دارد':'همسان'):'موجود'}</span></td></tr>})}</tbody></table>{!visible.length&&<div className={styles.empty}>رکوردی مطابق فیلتر پیدا نشد.</div>}</div></section>
 <aside className={styles.editor}><div className={styles.editorHead}><div><div className={styles.eyebrow}>EDITOR</div><div className={styles.editorTitle}>{selected?`ویرایش شبکه #${selected}`:'شبکه جدید'}</div></div>{selected&&<button className={styles.dangerBtn} onClick={()=>void remove()} disabled={busy}>حذف</button>}</div><div className={styles.form}>{field('name','نام فارسی')}{field('nameEn','نام انگلیسی')}{field('url','Stream URL',true)}{field('image','تصویر',true)}{field('category','دسته')}{field('categoryEn','دسته انگلیسی')}{field('catId','Category ID')}{field('popular','Popular')}<div className={styles.checks}><label className={styles.check}><input type="checkbox" checked={!!form.vpn} onChange={e=>patch('vpn',e.target.checked)}/> VPN</label><label className={styles.check}><input type="checkbox" checked={!!form.iran} onChange={e=>patch('iran',e.target.checked)}/> ایران</label><label className={styles.check}><input type="checkbox" checked={!!form.vip} onChange={e=>patch('vip',e.target.checked)}/> VIP</label></div>{field('referer','Referer')}{field('origin','Origin')}{field('country','Country')}{field('platform','Platform')}{field('satellite','Satellite')}{field('frequency','Frequency')}{field('polarization','Polarization')}{field('symbolRate','Symbol Rate')}{field('serviceId','Service ID')}<div className={styles.actions}><button onClick={()=>void save()} disabled={busy}>✓ ذخیره</button><button onClick={()=>{setSelected(null);setForm(blank)}}>پاک کردن</button></div></div>
 <div className={styles.sourceBox}><div className={styles.sourceHead}><strong>Sources · {form.sources.length}</strong><button onClick={addSource}>＋ Source</button></div>{form.sources.map((s,i)=><div className={styles.source} key={`${s.id}-${i}`}><div className={styles.note}>Source #{s.id??'جدید'}</div><input placeholder="عنوان" value={s.title||''} onChange={e=>sourcePatch(i,{title:e.target.value})}/><input placeholder="URL" dir="ltr" value={s.url} onChange={e=>sourcePatch(i,{url:e.target.value})}/><div className={styles.grid2}><input placeholder="Referer" dir="ltr" value={s.referer||''} onChange={e=>sourcePatch(i,{referer:e.target.value})}/><input placeholder="Origin" dir="ltr" value={s.origin||''} onChange={e=>sourcePatch(i,{origin:e.target.value})}/></div><div className={styles.sourceActions}><button className={styles.dangerBtn} onClick={()=>delSource(i)}>حذف Source</button></div></div>)}</div><p className={styles.note}>ویرایش در حالت CSV ابتدا محلی است؛ برای انتقال به DB از Sync استفاده کن. حذف کامل DB قابل بازگشت نیست.</p>{message&&<div className={styles.message}>{message}</div>}</aside></div></div></main>;
}