import crypto from 'node:crypto';
import { prisma } from './prisma';
import { matchChannel } from './channel-match';

type M3uEntry = { name: string; url: string; attrs: Record<string, string>; referer: string | null; origin: string | null };
export type M3uImportResult = { rows: number; created: number; updated: number; skipped: number; errors: string[]; channelsCreated: number; channelsMatched: number; sourcesCreated: number; sourcesSkipped: number };

function norm(value: unknown) { return String(value ?? '').normalize('NFKC').replace(/[يى]/g, 'ی').replace(/ك/g, 'ک').replace(/[\u064B-\u065F]/g, '').replace(/[\t\r\n]+/g, ' ').replace(/\s+/g, ' ').trim().toLowerCase(); }
function stableInt(key: string) { return Math.abs(Number.parseInt(crypto.createHash('sha1').update(key).digest('hex').slice(0, 7), 16)) || 1; }
function cleanUrl(value: string) { const raw = String(value ?? '').trim(); if (!raw || !/^https?:\/\//i.test(raw)) return ''; try { const url = new URL(raw); url.hash = ''; url.hostname = url.hostname.toLowerCase(); return url.toString().replace(/\/+$/, ''); } catch { return ''; } }
function parseAttributes(text: string) { const attrs: Record<string, string> = {}; const pattern = /([\w-]+)=(?:"([^"]*)"|([^\s]+))/g; let match: RegExpExecArray | null; while ((match = pattern.exec(text))) attrs[match[1].toLowerCase()] = (match[2] ?? match[3] ?? '').trim(); return attrs; }
function parseJsonHttpDirective(line: string) { try { const payload = JSON.parse(line.slice('#EXTHTTP:'.length).trim()) as Record<string, unknown>; const referer = payload.Referer ?? payload.referer ?? payload['http-referrer'] ?? payload['http-referer']; const origin = payload.Origin ?? payload.origin ?? payload['http-origin']; return { referer: referer ? String(referer).trim() : null, origin: origin ? String(origin).trim() : null }; } catch { return null; } }
function parseM3u(text: string): M3uEntry[] { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/); const entries: M3uEntry[] = []; let pending: Omit<M3uEntry, 'url'> | null = null; for (const rawLine of lines) { const line = rawLine.trim(); if (!line || line.startsWith('#EXTM3U')) continue; if (line.startsWith('#EXTINF:')) { const comma = line.indexOf(','); const header = comma >= 0 ? line.slice(8, comma) : line.slice(8); const displayName = comma >= 0 ? line.slice(comma + 1).trim() : ''; const attrs = parseAttributes(header); pending = { name: attrs['tvg-name'] || displayName || attrs['tvg-id'] || 'Unnamed channel', attrs, referer: null, origin: null }; continue; } if (line.startsWith('#EXTVLCOPT:') && pending) { const directive = line.slice('#EXTVLCOPT:'.length); const separator = directive.indexOf('='); const key = (separator >= 0 ? directive.slice(0, separator) : directive).trim().toLowerCase(); const value = separator >= 0 ? directive.slice(separator + 1).trim() : ''; if (key === 'http-referrer' || key === 'http-referer' || key === 'http-referrer-url') pending.referer = value || null; if (key === 'http-origin') pending.origin = value || null; continue; } if (line.startsWith('#EXTHTTP:') && pending) { const directive = parseJsonHttpDirective(line); if (directive?.referer) pending.referer = directive.referer; if (directive?.origin) pending.origin = directive.origin; continue; } if (line.startsWith('#')) continue; const url = cleanUrl(line); if (!pending || !url) continue; entries.push({ ...pending, url }); pending = null; } return entries; }
function categoryFor(entry: M3uEntry) { const group = (entry.attrs['group-title'] || '').split(/[;,|]/).map(v => v.trim()).filter(Boolean)[0] || ''; const value = norm(group); const known: Array<[RegExp, string, string]> = [[/news|خبر/, 'News', 'news'], [/sport|ورزش/, 'Sports', 'sports'], [/music|موزیک|موسیقی/, 'Music', 'music'], [/movie|film|فیلم|series|سریال/, 'Movies & Series', 'movies-series'], [/kids|child|کودک/, 'Kids', 'kids'], [/documentary|مستند/, 'Documentary', 'documentary'], [/relig|quran|قرآن|مذهبی/, 'Religion', 'religion'], [/entertain|سرگرمی/, 'Entertainment', 'entertainment']]; for (const [pattern, name, nameEn] of known) if (pattern.test(value)) return { name, nameEn }; return group ? { name: group, nameEn: group } : { name: 'Other', nameEn: 'other' }; }
async function ensureCategory(group: { name: string; nameEn: string }, cache: Map<string, number>) { const key = `${norm(group.name)}|${norm(group.nameEn)}`; const cached = cache.get(key); if (cached) return cached; const existing = await prisma.category.findFirst({ where: { OR: [{ name: group.name }, { nameEn: group.nameEn }] }, select: { id: true } }); if (existing) { cache.set(key, existing.id); return existing.id; } const id = stableInt(`m3u-category:${key}`); const collision = await prisma.category.findUnique({ where: { id }, select: { id: true } }); if (collision) { cache.set(key, id); return id; } const created = await prisma.category.create({ data: { id, name: group.name, nameEn: group.nameEn }, select: { id: true } }); cache.set(key, created.id); return id; }
async function uniqueChannelId(key: string) { let id = stableInt(`m3u-channel:${key}`); while (await prisma.channel.findUnique({ where: { id }, select: { id: true } })) id += 1; return id; }
async function uniqueSourceId(channelId: number, url: string) { let id = stableInt(`m3u-source:${channelId}:${url}`); while (await prisma.source.findUnique({ where: { id }, select: { id: true } })) id += 1; return id; }

export async function importM3u(text: string): Promise<M3uImportResult> { const entries = parseM3u(text); if (!entries.length) throw new Error('No valid HTTP(S) M3U entries were found.'); let created = 0, updated = 0, skipped = 0, channelsCreated = 0, channelsMatched = 0, sourcesCreated = 0, sourcesSkipped = 0; const errors: string[] = []; const channelCache = new Map<string, number>(); const categoryCache = new Map<string, number>(); const existingChannels = await prisma.channel.findMany({ select: { id: true, name: true, nameEn: true, catalogKey: true, url: true } });
  for (let i = 0; i < entries.length; i += 1) { const entry = entries[i]; try { const url = entry.url; const name = entry.name.trim() || entry.attrs['tvg-id'] || `Channel ${i + 1}`; const nameEn = entry.attrs['tvg-name'] || entry.attrs['tvg-id'] || name; const tvgId = entry.attrs['tvg-id'] || null; const catalogKey = `m3u:${norm(tvgId || nameEn)}`; const category = categoryFor(entry); const categoryId = await ensureCategory(category, categoryCache); const country = entry.attrs['tvg-country'] || entry.attrs['country'] || null; const language = entry.attrs['tvg-language'] || entry.attrs['language'] || null; const logo = entry.attrs['tvg-logo'] || entry.attrs['logo'] || null; const satellite = entry.attrs['satellite'] || entry.attrs['sat'] || null; const frequency = entry.attrs['frequency'] || entry.attrs['freq'] || null; const polarization = entry.attrs['polarization'] || entry.attrs['pol'] || null; const symbolRate = entry.attrs['symbolrate'] || entry.attrs['symbol-rate'] || entry.attrs['sr'] || null; const serviceId = entry.attrs['service-id'] || entry.attrs['serviceid'] || entry.attrs['sid'] || tvgId || null; const vpn = ['true', '1', 'yes'].includes(norm(entry.attrs['vpn'])); const iran = ['ir', 'iran'].includes(norm(country));
    let channelId = channelCache.get(catalogKey) || 0; let existing = channelId ? await prisma.channel.findUnique({ where: { id: channelId }, select: { id: true, catalogKey: true } }) : null; let matchReason = ''; if (!existing) { existing = await prisma.channel.findUnique({ where: { catalogKey }, select: { id: true, catalogKey: true } }); if (existing) channelId = existing.id; } if (!channelId) { const match = matchChannel({ name, nameEn, tvgId, url }, existingChannels); if (match.channel) { channelId = match.channel.id; matchReason = `${match.reason} (${Math.round(match.score * 100)}%)`; } } if (channelId) channelsMatched += 1;
    if (!channelId) { channelId = await uniqueChannelId(catalogKey); await prisma.channel.create({ data: { id: channelId, name, nameEn, catalogKey, image: logo, url, referer: entry.referer, origin: entry.origin, vpn, iran, popular: 0, vip: false, language, country, platform: satellite ? 'SATELLITE + INTERNET' : 'INTERNET', satellite, frequency, polarization, symbolRate, serviceId, categoryId, categoryName: category.name, categoryNameEn: category.nameEn } }); channelsCreated += 1; created += 1; existingChannels.push({ id: channelId, name, nameEn, catalogKey, url }); } else { const existingRow = existingChannels.find(channel => channel.id === channelId); const nextCatalogKey = existing?.catalogKey || existingRow?.catalogKey || catalogKey; const samePrimary = Boolean(existingRow?.url && cleanUrl(existingRow.url) === url); await prisma.channel.update({ where: { id: channelId }, data: { catalogKey: nextCatalogKey, image: logo || undefined, url: samePrimary ? undefined : url, referer: entry.referer || undefined, origin: entry.origin || undefined, language: language || undefined, country: country || undefined, platform: satellite ? 'SATELLITE + INTERNET' : undefined, satellite: satellite || undefined, frequency: frequency || undefined, polarization: polarization || undefined, symbolRate: symbolRate || undefined, serviceId: serviceId || undefined, categoryId, categoryName: category.name, categoryNameEn: category.nameEn, vpn: vpn || undefined, iran: iran || undefined } }); updated += 1; }
    channelCache.set(catalogKey, channelId); const duplicate = await prisma.source.findFirst({ where: { channelId, url }, select: { id: true } }); if (duplicate) { skipped += 1; sourcesSkipped += 1; continue; } await prisma.source.create({ data: { id: await uniqueSourceId(channelId, url), channelId, title: matchReason ? `${entry.name} • matched ${matchReason}` : entry.name, url, referer: entry.referer, origin: entry.origin, country, vip: false } }); created += 1; sourcesCreated += 1;
  } catch (error) { errors.push(`entry ${i + 1}: ${error instanceof Error ? error.message : 'import failed'}`); } }
  return { rows: entries.length, created, updated, skipped, errors, channelsCreated, channelsMatched, sourcesCreated, sourcesSkipped }; }
